apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-web-pvc
  namespace: httpd-with-pv
  labels:
    app: httpd-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi