apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-secrets-app
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: eso
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops-secrets/resources
    repoURL: https://github.com/joshgav/applications.git
    targetRevision: gitops-secrets
    kustomize: {}
  syncPolicy:
    automated: {}