apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-git-repo-creds
  namespace: eso
spec:
  secretStoreRef:
    name: awssm
    kind: ClusterSecretStore
  target:
    name: example-git-repo-creds
    template:
      metadata:
        annotations:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: '{{ .url }}'
        username: '{{ .username }}'
        password: '{{ .password }}'
  data:
  - secretKey: username
    remoteRef:
      key: git-repo-creds-02
      property: username
  - secretKey: password
    remoteRef:
      key: git-repo-creds-02
      property: password
  - secretKey: url
    remoteRef:
      key: git-repo-creds-02
      property: url