---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: awssm-secret
  namespace: eso
spec:
  encryptedData:
    access-key-id: AgDEey+6iyY1n2a1Boo+xJR4RZyD8w7evKFKL6d64Pmo0g0cUnHW56wZ82FQh1YbB/42zWaP5yQtQYeQAq94pdAbZ/n5q3oCp/CtaCBfxIZ2ouW6lHQpG2V1kvD6DspN9IEEWoeeXIBOfpjyCesjfHqyYWitybNxq2cXKUvlZGineDpiKpoH/u0UtTh1S3pyn4UEEWe8lLHQBVS1bK5WAhdbzmhrhgxsgUpmmhS5fwHJ0X+m3SEZ2zFNCPMR9zjVe6ElmRIl5JtLyLHd9CM1r86/QgJzIPnybeMTlkJczVdjZxQsqXb+mqSDZFmRw3euU6l+riN26cXgB6XP8cEhLhrqeKuILv/KllZL8gntHqRlsz7veZwfPdRS8K27avImhLaTuPMFCIQLGwUTwGh3xr0eNgg3Pp4H8IFaD+2HqEh2osrMUeFcvKGn5038YTFk8We/q0W7o6r887dw/epEgSxXuWv4s52+5xgyZiUR/Ref+l/YoH6BM2AdcJlPp7Ec9Azn0q6xZ/BFbnInvDz09mrhkBEsgpbFoZoajS3l/yv9YtzY8BgNQ26Y/nlRACiAllte/RKH4QaiHQ0Fx96nDLCg7PQbzelhRPbI0H2YueOxAheqyCpFiGvTOIqMEBTKYtaaz070J4hmjUCcFzVy73NG70b5AdkdyY+gfQoFGk961WSrcj/Fv0PPFZblhgA3/6SlJv0+edRBux2O0u5HQTeTnUsjww==
    secret-access-key: AgAn9x2bH6i2dy1Uh/obxXswV2iMciwFLgwyWjp8japSH7pmR0KKOn33CNUO20VAq1alVdDj4TBkKowPd0EZYel9RrpSghPkszUJL5tqwt/x4YotYJ03yq+QUPwV1Y8usZwD+qbjB2v9S16CNy1DmrbjODNHW+GoPYSMqnv7st7kXt7+giTa/yLIwDTKFFRNS4q/ekxCdid1uLCWjtyMtJJbeBfszkuC+PjELXzZ0qqFQgg2V2SKq0sDaVwlPO8H8E77aXGVex3zDogljVLNh7i8G1baLztq70UTx97xmaXDPIiCeqEvWvleV2OOZpt4DowAVJNYmWGIo4Z7u5N6iGUJZxidlbeF1FF80byzybavAw2LWMF+AG/IFpnHpw0+EnVKpq/FUN2cwDhnaFmje7oRNoCuESqyDwru1AD6zPEvPslyLJCGrcRfErP3wymian9/CvsHO5XXzr1hEFXSHeTyKhONC9gbj0BKI1h7j5n67et4hdHjKp2x9JE8zEZAxXB2NB+hfyFm8/SY/LG60nAKqLFTyu2r7m/RAh65Y5G22F2UYnenwVHXc5TeTgVMXUat9wcNUgR51PDAGCutkm7YZ6xiE6cP4SCa6igsKypEdwMUeK31GlT2gBpw1Z9/2tweG5cSlRoDMHORnmBs5AHJ9jgLlL6cTsk6FYlIXHsRcjY0b1pwiEZJWHsRp6AHP7VhOi6OtbVwDm9FRolUNPSQ7xyVBYlIUYJlcqCtN6lrv5+/cxsePZ7v
  template:
    metadata:
      creationTimestamp: null
      name: awssm-secret
      namespace: eso
    type: Opaque
