apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-secret01
  namespace: eso
spec:
  secretStoreRef:
    name: awssm
    kind: ClusterSecretStore
  target:
    name: aws-secret01
    template:
      metadata:
        annotations:
          joshgav.com/secret-type: secret-value-01
      data:
        type-test: value-test
        test-key-01: '{{ .testkey01 }}'
  data:
  - secretKey: testkey01
    remoteRef:
      key: aws-secret01
      property: test-key-01